# Generated by Django 5.2 on 2025-04-10 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('quantity_needed', models.FloatField()),
                ('urgency_level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('requester_name', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_pints', models.FloatField(default=0)),
                ('donor_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=3)),
                ('amount', models.FloatField()),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
