# Generated by Django 5.2 on 2025-05-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_alter_blooddonation_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='quantity_needed',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='requester_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgency_level',
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Rajpura', 'Rajpura'), ('Ludhiana', 'Ludhiana'), ('Bathinda', 'Bathinda'), ('Patiala', 'Patiala')], max_length=100),
        ),
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Rajpura', 'Rajpura'), ('Ludhiana', 'Ludhiana'), ('Bathinda', 'Bathinda'), ('Patiala', 'Patiala')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('organizer_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
