# Generated by Django 5.1.7 on 2025-05-06 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_remove_bloodrequest_quantity_needed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='available_pints',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donor_details',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='quantity_needed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
